####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2023. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
{{- if .Values.enableNginxServer }}
{{ $waUserName := include "wa.console.waUser" .}}
{{ $packagesUrl := include "waconsole.packagesUrl" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-deployment
  labels:
{{ include "wa.console.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-nginx-deployment
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-nginx-deployment
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.global.serviceAccountName | default $waUserName }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false     
            capabilities:
              drop:
              - ALL 
          image: "hclcr.io/wa/hcl-workload-automation-packages:10.2.1.00.20231201"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: packages.json
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: packages.json
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          env:
            - name: RELEASE_NAME
              value: {{ .Release.Name | quote }}
            - name: PACKAGES_URL
              value: {{ $packagesUrl }}
{{- end }}