apiVersion: v2
version: 10.2.5
appVersion: 10.2.5.00
description: Helm chart for configuring HCL Workload Automation.
keywords:
- Commercial
- amd64
- Workload Scheduler
- Workload Automation
- Automation
- DevOps
- ICP
kubeVersion: ">=1.14.0 || >=1.14.0-0"
maintainers:
- name: HCL Workload Automation
name: hcl-workload-automation-prod
dependencies:
  - name: wa-server-prod
    version: 10.2.5
    alias: waserver
    condition: waserver.enableServer
  - name: wa-console-prod
    version: 10.2.5
    alias: waconsole
    condition: waconsole.enableConsole
  - name: wa-dyn-agent-prod
    version: 10.2.5
    alias: waagent
    condition: waagent.enableAgent
  - name: wa-fileproxy-prod
    version: 10.2.5
    alias: wafileproxy
    condition: wafileproxy.enableFileProxy
  - name: wa-aida-prod
    version: 1.0.2
    alias: waaida
    condition: waaida.enableAIDA